# Site
repository: wahab1000/wahab1000.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Wahab Faizi
title: Electrical & Electronic Engineering Student | Developer & Problem Solver
email: wahabfaizi10@outlook.com
website: www.github.com/wahab1000

# Dark Mode
darkmode: false

# Social links
github_username: wahab1000
linkedin: www.linkedin.com/in/wahab-faizi

# About Section
about_profile_image: IMG_6655 2.jpg
about_content: |
  Hello, I'm Wahab Faizi—a second-year Electrical & Electronic Engineering student at Queen Mary University of London with a projected First-Class Honours. My academic work and extracurriculars bridge the gap between engineering and technology, combining both hands-on design and software development.

  I’m skilled in <mark>Python (Flask)</mark>, <mark>SQL</mark>, <mark>HTML/CSS</mark>, and have experience with <mark>Java</mark>, <mark>C</mark>, Docker, and Elasticsearch. Outside of coding, I co-founded the Circuit Design Society and regularly compete in Brazilian Jiu-Jitsu and Judo at a national level, where I’ve helped my team secure three consecutive national titles.

  Whether building autonomous robots or improving digital systems, I enjoy solving real-world problems at the intersection of hardware and software.

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: CogStack Catalogue App
        additional_links:
          - title: Project Presentation
            icon: fas fa-file-powerpoint
            url: https://qmulprod-my.sharepoint.com/:p:/r/personal/ec23245_qmul_ac_uk/Documents/CogStack%20Catalogue%20Presentation.pptx?d=w75b233c58ce84a4bb1a75bb187a2e665&csf=1&web=1&e=2C13kb
        description: |
          Worked on backend and frontend development for the healthcare-focused CogStack Catalogue app during a UCL internship. Optimised database queries using SQL, enhanced the backend with Flask, and improved the HTML-based user interface. Integrated Elasticsearch and Kibana for advanced data handling and visualisation.

      - layout: top-middle
        title: Autonomous Line-Following Robot
        additional_links:
          - title: GitHub Repository
            icon: fab fa-github
            url: https://github.com/wahab1000/Autonomous-Line-Following-and-Obstacle-Avoiding-Vehicle
        description: |
          Designed and built a self-navigating robot using an Arduino Nano. Programmed in embedded C for line-following and obstacle detection. Led the circuit design, sensor calibration, and system integration.

      - layout: top-middle
        title: Circuit Design Society
        description: |
          Co-founded this student-led society to promote practical electronics learning. Organised workshops on circuit design and coordinated events to help undergraduates enhance their technical confidence.

      - layout: top-middle
        title: Upcoming Projects
        description: |
          Currently working on automating data collection for healthcare research and building a web-based dashboard for data visualisation using Flask and SQL.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Software Developer Intern
        link: https://www.ucl.ac.uk
        sub_title: UCL, London
        caption: June 2024 - September 2024
        description: |
          Developed backend features in Python (Flask) and optimised SQL databases. Used Kibana and Elasticsearch for visualising healthcare data. Improved user experience through HTML interface updates and explored basic natural language processing and AI model training.

      - layout: left
        title: Assistant BJJ Coach
        sub_title: Carlson Gracie London
        caption: January 2025 – Present
        description: |
          Began coaching children aged 3–16 in Brazilian Jiu-Jitsu. Adapted teaching methods to suit a range of age groups and learning styles. Built communication, leadership, and mentoring skills while supporting a positive, disciplined team environment.

      - layout: left
        title: Engineering Intern
        link: https://www.burohappold.com
        sub_title: Buro Happold, London
        caption: October 2022 (1 month)
        description: |
          Contributed to international infrastructure projects, including The Line in Saudi Arabia. Designed an electrical system for a high-rise building in Athens. Worked closely with IT, electrical, and structural teams on smart city concepts.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Queen Mary University of London
        caption: 2023 - Present
        sub_title: BEng Electrical & Electronic Engineering (Projected First-Class Honours)
        description: |
          Achieved First-Class grades in core modules: Digital Circuit Design (100%), Electronic Engineering Mathematics (99.1%), Engineering Skills & Practice (95.1%). Co-founded the Circuit Design Society and led workshops on electronics fundamentals.

      - layout: left
        title: Isleworth & Syon School
        caption: 2016 - 2023
        sub_title: A-Levels in Mathematics (A), Physics (B), Economics (B)
        description: |
          Held leadership roles as House Captain and Sports Captain. Organised student-led events and guided peers in academic and extracurricular activities.

  - title: A Little More About Me
    layout: text
    content: |
      I’m a national-level Brazilian Jiu-Jitsu and Judo competitor, representing Carlson Gracie London. As an athlete, I’ve helped my team secure three consecutive national titles, which has greatly developed my discipline, strategic thinking, and resilience under pressure.

      Since January 2025, I’ve also taken on a coaching role, teaching children aged 3–16. This has strengthened my communication and mentoring abilities, as I work to build confidence and focus in young learners.

      Beyond martial arts, I’ve organised three charity sports tournaments at my local youth centre and am currently planning a university-wide 5K charity run. Community engagement and leadership are core to who I am.

# Footer
footer_show_references: true
references_title: References available on request

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
