# Site
repository: wahab1000/wahab1000.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Wahab Faizi
title: Electrical & Electronic Engineering Student | Developer & Problem Solver
email: wahabfaizi10@outlook.com
website: www.github.com/wahab1000

# Dark Mode
darkmode: false

# Social links (icons appear top-right)
github_username: wahab1000
linkedin: wahab-faizi

# About Section
about_profile_image: IMG_6655 2.jpg
about_content: |
  Hello, I'm Wahab Faizi — a third-year Electrical & Electronic Engineering student at Queen Mary University of London with a projected First-Class Honours. I bridge the gap between hardware and software through engineering design, software development, and AI experimentation.

  My core skills include <mark>Python (Flask)</mark>, <mark>SQL</mark>, <mark>HTML/CSS</mark>, <mark>Java</mark>, <mark>C</mark>, <mark>Elasticsearch</mark>, <mark>Kibana</mark>, and embedded systems using Arduino. I also work with tools like Docker and have growing experience in <mark>AI</mark> and <mark>NLP</mark> model development.

  Beyond technical skills, I co-founded a student society, coach youth athletes, and actively contribute to the FinTech Society, where I explore how technology can drive innovation in finance. These experiences demonstrate initiative, teamwork, and leadership — qualities I bring to every environment I’m part of.

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: AI Fight Analysis Tool (Ongoing)
        description: |
          Designing an AI-powered application that analyses MMA and Brazilian Jiu-Jitsu sparring/fight footage. Using <mark>pose estimation</mark> and <mark>machine learning</mark>, the tool will detect dominant positions (e.g., <mark>mount</mark>, <mark>guard</mark>, <mark>back control</mark>), build positional timelines, and generate performance statistics. The goal is to help athletes and coaches identify strengths and weaknesses and sharpen strategy.
          
          Current work: data pipeline design, baseline position detection, and evaluation metrics. Planned: web dashboard with <mark>Flask</mark>, <mark>SQL</mark>, and visual analytics, plus optional real-time feedback.

      - layout: top-middle
        title: CogStack Catalogue App
        additional_links:
          - title: Project Presentation
            icon: fas fa-file-powerpoint
            url: https://qmulprod-my.sharepoint.com/:p:/r/personal/ec23245_qmul_ac_uk/Documents/CogStack%20Catalogue%20Presentation.pptx?d=w75b233c58ce84a4bb1a75bb187a2e665&csf=1&web=1&e=2C13kb
        description: |
          Developed features for a healthcare data request platform during my internship at UCL. Built APIs with <mark>Flask</mark> and <mark>Python</mark>, improved <mark>SQL</mark> query performance, and integrated <mark>Elasticsearch</mark> and <mark>Kibana</mark> for interactive dashboards. Enhanced the <mark>HTML</mark> UI for better usability. Gained exposure to <mark>NLP</mark> workflows and ethical, privacy-first handling of clinical data.

      - layout: top-middle
        title: Autonomous Line-Following Robot
        additional_links:
          - title: GitHub Repository
            icon: fab fa-github
            url: https://github.com/wahab1000/Autonomous-Line-Following-and-Obstacle-Avoiding-Vehicle
        description: |
          Designed and built a robot using an <mark>Arduino Nano</mark> that autonomously follows lines and avoids obstacles. Programmed in <mark>C</mark>, designed circuit schematics, and integrated IR sensors for real-time path tracking. Demonstrated skills in <mark>embedded systems</mark>, <mark>sensor calibration</mark>, and <mark>system integration</mark>.

      - layout: top-middle
        title: Circuit Design Society
        description: |
          Co-founded a society focused on hands-on electronics. Designed and led <mark>practical workshops</mark> in <mark>digital circuit design</mark> and <mark>breadboarding</mark> for first-year students. Experience in <mark>leadership</mark>, <mark>public speaking</mark>, <mark>curriculum planning</mark>, and peer mentorship.

      - layout: top-middle
        title: Upcoming Projects
        description: |
          Collaborating on a web application that uses <mark>AI</mark> and <mark>web scraping</mark> to help users find the best online deals. The user inputs a product name, and the app searches multiple marketplaces (e.g. Facebook Marketplace, eBay), comparing listings and recommending the best value. Built with <mark>Python</mark>, <mark>Flask</mark>, and <mark>SQL</mark> on the backend, and <mark>HTML</mark> for the frontend.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Software Developer 
        link: https://www.ucl.ac.uk
        sub_title: UCL, London
        caption: June 2024 - September 2024
        description: |
          Built backend features during my internship in <mark>Python</mark> using <mark>Flask</mark>, managed healthcare data with <mark>SQL</mark>, and applied <mark>Elasticsearch</mark>/<mark>Kibana</mark> for search and dashboards. Improved the <mark>HTML</mark> UI and collaborated in agile sprints. Developed early-stage familiarity with <mark>AI</mark> and <mark>NLP</mark> for medical text.

      - layout: left
        title: Engineer
        link: https://www.burohappold.com
        sub_title: Buro Happold, London
        caption: October 2022
        description: |
          Contributed to multidisciplinary teams on international projects including <mark>The Line</mark> (Saudi Arabia), during a short term internship role. Created a modular <mark>electrical system</mark> sketch for a high-rise in Athens. Gained exposure to <mark>smart city infrastructure</mark>, <mark>technical drawing</mark>, and collaborative design with IT and structural engineers.

      - layout: left
        title: Assistant BJJ Coach
        sub_title: Carlson Gracie London
        caption: January 2025 – Present
        description: |
          Coach children aged 3–16 in Brazilian Jiu-Jitsu, tailoring teaching styles to varied needs. Developed <mark>mentorship</mark>, <mark>adaptability</mark>, <mark>communication</mark>, and <mark>leadership</mark> while fostering a supportive and disciplined training environment.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Queen Mary University of London
        caption: 2023 - Present
        sub_title: BEng Electrical & Electronic Engineering (Projected First-Class Honours)
        description: |
          First-Class grades in modules including <mark>Digital Circuit Design (100%)</mark>, <mark>Electronic Engineering Mathematics (99.1%)</mark>, and <mark>Engineering Skills & Practise (95.1%)</mark>. Built strengths in <mark>hardware design</mark>, <mark>signal processing</mark>, and <mark>project management</mark>. Active member of the FinTech Society, engaging with applications of technology in financial systems.

      - layout: left
        title: Isleworth & Syon School
        caption: 2016 - 2023
        sub_title: A-Levels in Mathematics (A), Physics (B), Economics (B)
        description: |
          Held roles as House Captain and Sports Captain. Organised initiatives and demonstrated leadership across academics and extracurriculars.

  - title: Consulting & Transferable Skills
    layout: text
    content: |
      Beyond engineering and software, I bring consulting-relevant skills that apply across industries:

      - **Analytical problem-solving**: proven through engineering internships and data-driven projects.  
      - **Communication & presentation**: experience delivering technical findings to stakeholders.  
      - **Leadership & mentoring**: co-founder of a society, FinTech Society member, and youth sports coach.  
      - **Project coordination**: managed group projects, balancing deadlines and team roles.  
      - **Financial awareness**: involvement in FinTech Society and economics background highlight interest in finance within STEM.  
      - **Community engagement**: organised charity events and collaborated with societies on fundraising.

      These experiences show I can apply my engineering mindset not only in technical roles but also in consulting, fintech, and finance-related industries.

  - title: A Little More About Me
    layout: text
    content: |
      I’m a national-level Brazilian Jiu-Jitsu and Judo competitor with three consecutive national titles, sharpening my <mark>resilience</mark>, <mark>strategic thinking</mark>, and <mark>composure under pressure</mark>.

      Since 2025, I’ve coached youth classes, instilling <mark>discipline</mark>, <mark>confidence</mark>, and <mark>focus</mark> in students aged 3–16. This experience strengthened my <mark>mentoring</mark>, <mark>communication</mark>, and <mark>leadership</mark> skills.

      I’ve organised three charity sports tournaments and am planning a 5K charity run with university societies. Whether in athletics, engineering, fintech, or community work, I bring initiative and a team-first mindset.

# Footer
footer_show_references: true
references_title: References available on request

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

# SEO settings
title: "Wahab Faizi | Engineering, FinTech & Consulting"
description: "Wahab Faizi – Electrical & Electronic Engineering student at Queen Mary University of London. Interests in software, AI, consulting, and FinTech. Skilled in Python, SQL, Flask, and embedded systems. Active member of FinTech Society and experienced in leadership, teamwork, and problem-solving."
keywords: "Wahab Faizi, Engineering Student, Electrical Engineering, Software Developer, FinTech, Finance, Consulting, AI, Python, SQL, Flask, Embedded Systems, University of London"

plugins:
 - jekyll-seo-tag



